### ISSUE TITLE
EPIC | ABI encoding

### ISSUE THREAD

**Issue by poplexity** [telosnetwork/antelope-rs#10]
## Overview
Support all ABI types and decoding binary from an ABI.

## Links
[Typestresser ABI from WharfKit](https://github.com/telosnetwork/antelope-rs/blob/master/crates/antelope/tests/typestresser.abi.json)

## Acceptance Criteria
An ABI structure with a from_str or from_json constructor function.  Given that ABI structure, or a typedef from it, deserialize binary data into an untyped structure.  As you cannot define a struct at runtime, if the ABI defines a type called `Applesauce` with some fields on it, we cannot return an `Applesauce` struct, so we need a generic type that can represent any ABI type (i.e. `Map<String, Packer>` or an enum with that map or just a `Packer` itself)

## Tasks

- [ ] Implement `Packer` for all Antelope types
- [ ] Implement `ABI` struct
- [ ] Implement a generic container for deserializing into
- [ ] Implement deserialization from binary into the generic container
